//
// Generated by Tools/GenerateTAE3Events.py from SoulsFormats' TAE3.Event.cs. Do not edit by hand.
//

#pragma once

#include <libSouls/BinaryReader.hpp>
#include <libSouls/BinaryWriter.hpp>

#include <cstdint>
#include <variant>
#include <vector>

namespace Souls {

    // Determines the behavior of an event and what data it contains.
    enum class TAE3EventType : uint64_t {
        JumpTable = 0,
        Unk001 = 1,
        Unk002 = 2,
        Unk005 = 5,
        Unk016 = 16,
        Unk017 = 17,
        Unk024 = 24,
        SwitchWeapon1 = 32,
        SwitchWeapon2 = 33,
        Unk034 = 34,
        Unk035 = 35,
        Unk064 = 64,
        Unk065 = 65,
        CreateSpEffect1 = 66,
        CreateSpEffect2 = 67,
        PlayFFX = 96,
        Unk110 = 110,
        HitEffect = 112,
        Unk113 = 113,
        Unk114 = 114,
        Unk115 = 115,
        Unk116 = 116,
        Unk117 = 117,
        Unk118 = 118,
        Unk119 = 119,
        Unk120 = 120,
        Unk121 = 121,
        PlaySound1 = 128,
        PlaySound2 = 129,
        PlaySound3 = 130,
        PlaySound4 = 131,
        PlaySound5 = 132,
        Unk136 = 136,
        Unk137 = 137,
        CreateDecal = 138,
        Unk144 = 144,
        Unk145 = 145,
        Unk150 = 150,
        Unk151 = 151,
        Unk161 = 161,
        Unk192 = 192,
        FadeOut = 193,
        Unk194 = 194,
        Unk224 = 224,
        DisableStaminaRegen = 225,
        Unk226 = 226,
        Unk227 = 227,
        RagdollReviveTime = 228,
        Unk229 = 229,
        SetEventMessageID = 231,
        Unk232 = 232,
        ChangeDrawMask = 233,
        RollDistanceReduction = 236,
        CreateAISound = 237,
        Unk300 = 300,
        Unk301 = 301,
        AddSpEffectDragonForm = 302,
        PlayAnimation = 303,
        BehaviorThing = 304,
        Unk306 = 306,
        CreateBehaviorPC = 307,
        Unk308 = 308,
        Unk310 = 310,
        Unk311 = 311,
        Unk312 = 312,
        Unk317 = 317,
        Unk320 = 320,
        Unk330 = 330,
        EffectDuringThrow = 331,
        Unk332 = 332,
        CreateSpEffect = 401,
        Unk500 = 500,
        Unk510 = 510,
        Unk520 = 520,
        KingOfTheStorm = 522,
        Unk600 = 600,
        Unk601 = 601,
        DebugAnimSpeed = 603,
        Unk605 = 605,
        Unk606 = 606,
        Unk700 = 700,
        EnableTurningDirection = 703,
        FacingAngleCorrection = 705,
        Unk707 = 707,
        HideWeapon = 710,
        HideModelMask = 711,
        DamageLevelModule = 712,
        ModelMask = 713,
        DamageLevelFunction = 714,
        Unk715 = 715,
        CultStart = 720,
        Unk730 = 730,
        Unk740 = 740,
        IFrameState = 760,
        BonePos = 770,
        BoneFixOn1 = 771,
        BoneFixOn2 = 772,
        TurnLowerBody = 781,
        Unk782 = 782,
        SpawnBulletByCultSacrifice1 = 785,
        Unk786 = 786,
        Unk790 = 790,
        Unk791 = 791,
        HitEffect2 = 792,
        CultSacrifice1 = 793,
        SacrificeEmpty = 794,
        Toughness = 795,
        BringCultMenu = 796,
        CeremonyParamID = 797,
        CultSingle = 798,
        CultEmpty2 = 799,
        Unk800 = 800,
        Unk900 = 900,
    };

    // One struct per event type, holding the fields that follow the event's header in the file.
    namespace TAE3Events {

    struct JumpTable {
        static constexpr TAE3EventType Type = TAE3EventType::JumpTable;
        int32_t JumpTableID = {};
        int32_t Unk04 = {};
        int32_t Unk08 = {};
        int16_t Unk0C = {};
        int16_t Unk0E = {};

        void Read(BinaryReader& Reader) {
            JumpTableID = Reader.ReadInt32();
            Unk04 = Reader.ReadInt32();
            Unk08 = Reader.ReadInt32();
            Unk0C = Reader.ReadInt16();
            Unk0E = Reader.ReadInt16();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(JumpTableID);
            Writer.WriteInt32(Unk04);
            Writer.WriteInt32(Unk08);
            Writer.WriteInt16(Unk0C);
            Writer.WriteInt16(Unk0E);
        }
    };

    struct Unk001 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk001;
        int32_t Unk00 = {};
        int32_t Unk04 = {};
        int32_t Condition = {};
        uint8_t Unk0C = {};
        uint8_t Unk0D = {};
        int16_t StateInfo = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadInt32();
            Condition = Reader.ReadInt32();
            Unk0C = Reader.ReadByte();
            Unk0D = Reader.ReadByte();
            StateInfo = Reader.ReadInt16();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteInt32(Unk04);
            Writer.WriteInt32(Condition);
            Writer.WriteByte(Unk0C);
            Writer.WriteByte(Unk0D);
            Writer.WriteInt16(StateInfo);
        }
    };

    struct Unk002 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk002;
        int32_t Unk00 = {};
        int32_t Unk04 = {};
        int32_t ChrAsmStyle = {};
        uint8_t Unk0C = {};
        uint8_t Unk0D = {};
        uint16_t Unk0E = {};
        uint16_t Unk10 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadInt32();
            ChrAsmStyle = Reader.ReadInt32();
            Unk0C = Reader.ReadByte();
            Unk0D = Reader.ReadByte();
            Unk0E = Reader.ReadUInt16();
            Unk10 = Reader.ReadUInt16();
            Reader.Assert<int16_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteInt32(Unk04);
            Writer.WriteInt32(ChrAsmStyle);
            Writer.WriteByte(Unk0C);
            Writer.WriteByte(Unk0D);
            Writer.WriteUInt16(Unk0E);
            Writer.WriteUInt16(Unk10);
            Writer.WriteInt16(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk005 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk005;
        int32_t Unk00 = {};
        int32_t Unk04 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadInt32();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteInt32(Unk04);
        }
    };

    struct Unk016 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk016;

        void Read(BinaryReader& Reader) {
            (void)Reader;
        }

        void Write(BinaryWriter& Writer) const {
            (void)Writer;
        }
    };

    struct Unk017 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk017;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk024 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk024;
        int32_t Unk00 = {};
        int32_t Unk04 = {};
        int32_t Unk08 = {};
        int32_t Unk0C = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadInt32();
            Unk08 = Reader.ReadInt32();
            Unk0C = Reader.ReadInt32();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteInt32(Unk04);
            Writer.WriteInt32(Unk08);
            Writer.WriteInt32(Unk0C);
        }
    };

    struct SwitchWeapon1 {
        static constexpr TAE3EventType Type = TAE3EventType::SwitchWeapon1;
        int32_t SwitchState = {};

        void Read(BinaryReader& Reader) {
            SwitchState = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(SwitchState);
            Writer.WriteInt32(0);
        }
    };

    struct SwitchWeapon2 {
        static constexpr TAE3EventType Type = TAE3EventType::SwitchWeapon2;
        int32_t SwitchState = {};

        void Read(BinaryReader& Reader) {
            SwitchState = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(SwitchState);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk034 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk034;
        int32_t State = {};

        void Read(BinaryReader& Reader) {
            State = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(State);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk035 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk035;
        int32_t State = {};

        void Read(BinaryReader& Reader) {
            State = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(State);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk064 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk064;
        int32_t Unk00 = {};
        uint16_t Unk04 = {};
        uint16_t Unk06 = {};
        uint8_t Unk08 = {};
        uint8_t Unk09 = {};
        uint8_t Unk0A = {};
        uint8_t Unk0B = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadUInt16();
            Unk06 = Reader.ReadUInt16();
            Unk08 = Reader.ReadByte();
            Unk09 = Reader.ReadByte();
            Unk0A = Reader.ReadByte();
            Unk0B = Reader.ReadByte();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteUInt16(Unk04);
            Writer.WriteUInt16(Unk06);
            Writer.WriteByte(Unk08);
            Writer.WriteByte(Unk09);
            Writer.WriteByte(Unk0A);
            Writer.WriteByte(Unk0B);
            Writer.WriteInt32(0);
        }
    };

    struct Unk065 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk065;
        int32_t Unk00 = {};
        uint8_t Unk04 = {};
        uint8_t Unk05 = {};
        uint16_t Unk06 = {};
        int32_t Unk08 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadByte();
            Unk05 = Reader.ReadByte();
            Unk06 = Reader.ReadUInt16();
            Unk08 = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteByte(Unk04);
            Writer.WriteByte(Unk05);
            Writer.WriteUInt16(Unk06);
            Writer.WriteInt32(Unk08);
            Writer.WriteInt32(0);
        }
    };

    struct CreateSpEffect1 {
        static constexpr TAE3EventType Type = TAE3EventType::CreateSpEffect1;
        int32_t SpEffectID = {};

        void Read(BinaryReader& Reader) {
            SpEffectID = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(SpEffectID);
            Writer.WriteInt32(0);
        }
    };

    struct CreateSpEffect2 {
        static constexpr TAE3EventType Type = TAE3EventType::CreateSpEffect2;
        int32_t SpEffectID = {};

        void Read(BinaryReader& Reader) {
            SpEffectID = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(SpEffectID);
            Writer.WriteInt32(0);
        }
    };

    struct PlayFFX {
        static constexpr TAE3EventType Type = TAE3EventType::PlayFFX;
        int32_t FFXID = {};
        int32_t Unk04 = {};
        int32_t Unk08 = {};
        int8_t State0 = {};
        int8_t State1 = {};
        int8_t GhostFFXCondition = {};
        uint8_t Unk0F = {};

        void Read(BinaryReader& Reader) {
            FFXID = Reader.ReadInt32();
            Unk04 = Reader.ReadInt32();
            Unk08 = Reader.ReadInt32();
            State0 = Reader.ReadSByte();
            State1 = Reader.ReadSByte();
            GhostFFXCondition = Reader.ReadSByte();
            Unk0F = Reader.ReadByte();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(FFXID);
            Writer.WriteInt32(Unk04);
            Writer.WriteInt32(Unk08);
            Writer.WriteSByte(State0);
            Writer.WriteSByte(State1);
            Writer.WriteSByte(GhostFFXCondition);
            Writer.WriteByte(Unk0F);
        }
    };

    struct Unk110 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk110;
        int32_t ID = {};

        void Read(BinaryReader& Reader) {
            ID = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(ID);
            Writer.WriteInt32(0);
        }
    };

    struct HitEffect {
        static constexpr TAE3EventType Type = TAE3EventType::HitEffect;
        int32_t Size = {};
        int32_t Unk04 = {};
        int32_t Unk08 = {};

        void Read(BinaryReader& Reader) {
            Size = Reader.ReadInt32();
            Unk04 = Reader.ReadInt32();
            Unk08 = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Size);
            Writer.WriteInt32(Unk04);
            Writer.WriteInt32(Unk08);
            Writer.WriteInt32(0);
        }
    };

    struct Unk113 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk113;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk114 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk114;
        int32_t Unk00 = {};
        uint16_t Unk04 = {};
        uint16_t Unk06 = {};
        int32_t Unk08 = {};
        uint8_t Unk0C = {};
        int8_t Unk0D = {};
        int8_t Unk0E = {};
        uint8_t Unk0F = {};
        uint8_t Unk10 = {};
        uint8_t Unk11 = {};
        int16_t Unk12 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadUInt16();
            Unk06 = Reader.ReadUInt16();
            Unk08 = Reader.ReadInt32();
            Unk0C = Reader.ReadByte();
            Unk0D = Reader.ReadSByte();
            Unk0E = Reader.ReadSByte();
            Unk0F = Reader.ReadByte();
            Unk10 = Reader.ReadByte();
            Unk11 = Reader.ReadByte();
            Unk12 = Reader.ReadInt16();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteUInt16(Unk04);
            Writer.WriteUInt16(Unk06);
            Writer.WriteInt32(Unk08);
            Writer.WriteByte(Unk0C);
            Writer.WriteSByte(Unk0D);
            Writer.WriteSByte(Unk0E);
            Writer.WriteByte(Unk0F);
            Writer.WriteByte(Unk10);
            Writer.WriteByte(Unk11);
            Writer.WriteInt16(Unk12);
            Writer.WriteInt32(0);
        }
    };

    struct Unk115 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk115;
        int32_t Unk00 = {};
        uint16_t Unk04 = {};
        uint16_t Unk06 = {};
        int32_t Unk08 = {};
        uint8_t Unk0C = {};
        uint8_t Unk0D = {};
        uint8_t Unk0E = {};
        uint8_t Unk0F = {};
        uint8_t Unk10 = {};
        uint8_t Unk11 = {};
        int16_t Unk12 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadUInt16();
            Unk06 = Reader.ReadUInt16();
            Unk08 = Reader.ReadInt32();
            Unk0C = Reader.ReadByte();
            Unk0D = Reader.ReadByte();
            Unk0E = Reader.ReadByte();
            Unk0F = Reader.ReadByte();
            Unk10 = Reader.ReadByte();
            Unk11 = Reader.ReadByte();
            Unk12 = Reader.ReadInt16();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteUInt16(Unk04);
            Writer.WriteUInt16(Unk06);
            Writer.WriteInt32(Unk08);
            Writer.WriteByte(Unk0C);
            Writer.WriteByte(Unk0D);
            Writer.WriteByte(Unk0E);
            Writer.WriteByte(Unk0F);
            Writer.WriteByte(Unk10);
            Writer.WriteByte(Unk11);
            Writer.WriteInt16(Unk12);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk116 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk116;
        int32_t Unk00 = {};
        int32_t Unk04 = {};
        int32_t Unk08 = {};
        int32_t Unk0C = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadInt32();
            Unk08 = Reader.ReadInt32();
            Unk0C = Reader.ReadInt32();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteInt32(Unk04);
            Writer.WriteInt32(Unk08);
            Writer.WriteInt32(Unk0C);
        }
    };

    struct Unk117 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk117;
        int32_t Unk00 = {};
        int32_t Unk04 = {};
        int32_t Unk08 = {};
        uint8_t Unk0C = {};
        uint8_t Unk0D = {};
        uint8_t Unk0E = {};
        uint8_t Unk0F = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadInt32();
            Unk08 = Reader.ReadInt32();
            Unk0C = Reader.ReadByte();
            Unk0D = Reader.ReadByte();
            Unk0E = Reader.ReadByte();
            Unk0F = Reader.ReadByte();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteInt32(Unk04);
            Writer.WriteInt32(Unk08);
            Writer.WriteByte(Unk0C);
            Writer.WriteByte(Unk0D);
            Writer.WriteByte(Unk0E);
            Writer.WriteByte(Unk0F);
        }
    };

    struct Unk118 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk118;
        int32_t Unk00 = {};
        uint16_t Unk04 = {};
        uint16_t Unk06 = {};
        uint16_t Unk08 = {};
        uint16_t Unk0A = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadUInt16();
            Unk06 = Reader.ReadUInt16();
            Unk08 = Reader.ReadUInt16();
            Unk0A = Reader.ReadUInt16();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteUInt16(Unk04);
            Writer.WriteUInt16(Unk06);
            Writer.WriteUInt16(Unk08);
            Writer.WriteUInt16(Unk0A);
            Writer.WriteInt32(0);
        }
    };

    struct Unk119 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk119;
        int32_t Unk00 = {};
        int32_t Unk04 = {};
        int32_t Unk08 = {};
        uint8_t Unk0C = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadInt32();
            Unk08 = Reader.ReadInt32();
            Unk0C = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteInt32(Unk04);
            Writer.WriteInt32(Unk08);
            Writer.WriteByte(Unk0C);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
        }
    };

    struct Unk120 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk120;
        int32_t ChrType = {};
        std::vector<int32_t> FFXIDs = std::vector<int32_t>(11);
        int32_t Unk30 = {};
        int32_t Unk34 = {};
        uint8_t Unk38 = {};

        void Read(BinaryReader& Reader) {
            ChrType = Reader.ReadInt32();
            FFXIDs = Reader.ReadArray<int32_t>(11);
            Unk30 = Reader.ReadInt32();
            Unk34 = Reader.ReadInt32();
            Unk38 = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(ChrType);
            Writer.WriteArray(FFXIDs);
            Writer.WriteInt32(Unk30);
            Writer.WriteInt32(Unk34);
            Writer.WriteByte(Unk38);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk121 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk121;
        int32_t Unk00 = {};
        uint16_t Unk04 = {};
        uint8_t Unk06 = {};
        uint8_t Unk07 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadUInt16();
            Unk06 = Reader.ReadByte();
            Unk07 = Reader.ReadByte();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteUInt16(Unk04);
            Writer.WriteByte(Unk06);
            Writer.WriteByte(Unk07);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct PlaySound1 {
        static constexpr TAE3EventType Type = TAE3EventType::PlaySound1;
        int32_t SoundType = {};
        int32_t SoundID = {};

        void Read(BinaryReader& Reader) {
            SoundType = Reader.ReadInt32();
            SoundID = Reader.ReadInt32();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(SoundType);
            Writer.WriteInt32(SoundID);
        }
    };

    struct PlaySound2 {
        static constexpr TAE3EventType Type = TAE3EventType::PlaySound2;
        int32_t SoundType = {};
        int32_t SoundID = {};
        int32_t Unk08 = {};
        int32_t Unk0C = {};
        int32_t Unk10 = {};

        void Read(BinaryReader& Reader) {
            SoundType = Reader.ReadInt32();
            SoundID = Reader.ReadInt32();
            Unk08 = Reader.ReadInt32();
            Unk0C = Reader.ReadInt32();
            Unk10 = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(SoundType);
            Writer.WriteInt32(SoundID);
            Writer.WriteInt32(Unk08);
            Writer.WriteInt32(Unk0C);
            Writer.WriteInt32(Unk10);
            Writer.WriteInt32(0);
        }
    };

    struct PlaySound3 {
        static constexpr TAE3EventType Type = TAE3EventType::PlaySound3;
        int32_t SoundType = {};
        int32_t SoundID = {};
        float Unk08 = {};
        float Unk0C = {};

        void Read(BinaryReader& Reader) {
            SoundType = Reader.ReadInt32();
            SoundID = Reader.ReadInt32();
            Unk08 = Reader.ReadFloat();
            Unk0C = Reader.ReadFloat();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(SoundType);
            Writer.WriteInt32(SoundID);
            Writer.WriteFloat(Unk08);
            Writer.WriteFloat(Unk0C);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct PlaySound4 {
        static constexpr TAE3EventType Type = TAE3EventType::PlaySound4;
        int32_t SoundType = {};
        int32_t SoundID = {};
        int32_t Unk08 = {};

        void Read(BinaryReader& Reader) {
            SoundType = Reader.ReadInt32();
            SoundID = Reader.ReadInt32();
            Unk08 = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(SoundType);
            Writer.WriteInt32(SoundID);
            Writer.WriteInt32(Unk08);
            Writer.WriteInt32(0);
        }
    };

    struct PlaySound5 {
        static constexpr TAE3EventType Type = TAE3EventType::PlaySound5;
        int32_t SoundType = {};
        int32_t SoundID = {};

        void Read(BinaryReader& Reader) {
            SoundType = Reader.ReadInt32();
            SoundID = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(SoundType);
            Writer.WriteInt32(SoundID);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk137 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk137;
        int32_t Unk00 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteInt32(0);
        }
    };

    struct CreateDecal {
        static constexpr TAE3EventType Type = TAE3EventType::CreateDecal;
        int32_t DecalParamID = {};
        int32_t Unk04 = {};

        void Read(BinaryReader& Reader) {
            DecalParamID = Reader.ReadInt32();
            Unk04 = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(DecalParamID);
            Writer.WriteInt32(Unk04);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk144 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk144;
        uint16_t Unk00 = {};
        uint16_t Unk02 = {};
        float Unk04 = {};
        float Unk08 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadUInt16();
            Unk02 = Reader.ReadUInt16();
            Unk04 = Reader.ReadFloat();
            Unk08 = Reader.ReadFloat();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteUInt16(Unk00);
            Writer.WriteUInt16(Unk02);
            Writer.WriteFloat(Unk04);
            Writer.WriteFloat(Unk08);
            Writer.WriteInt32(0);
        }
    };

    struct Unk145 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk145;
        int16_t Unk00 = {};
        int16_t Condition = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt16();
            Condition = Reader.ReadInt16();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt16(Unk00);
            Writer.WriteInt16(Condition);
            Writer.WriteInt32(0);
        }
    };

    struct Unk150 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk150;
        int32_t Unk00 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk151 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk151;
        int32_t DummyPointID = {};

        void Read(BinaryReader& Reader) {
            DummyPointID = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(DummyPointID);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk161 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk161;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct FadeOut {
        static constexpr TAE3EventType Type = TAE3EventType::FadeOut;
        float GhostVal1 = {};
        float GhostVal2 = {};

        void Read(BinaryReader& Reader) {
            GhostVal1 = Reader.ReadFloat();
            GhostVal2 = Reader.ReadFloat();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteFloat(GhostVal1);
            Writer.WriteFloat(GhostVal2);
        }
    };

    struct Unk194 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk194;
        uint16_t Unk00 = {};
        uint16_t Unk02 = {};
        uint16_t Unk04 = {};
        uint16_t Unk06 = {};
        float Unk08 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadUInt16();
            Unk02 = Reader.ReadUInt16();
            Unk04 = Reader.ReadUInt16();
            Unk06 = Reader.ReadUInt16();
            Unk08 = Reader.ReadFloat();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteUInt16(Unk00);
            Writer.WriteUInt16(Unk02);
            Writer.WriteUInt16(Unk04);
            Writer.WriteUInt16(Unk06);
            Writer.WriteFloat(Unk08);
            Writer.WriteInt32(0);
        }
    };

    struct Unk224 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk224;
        float Unk00 = {};
        int32_t Unk04 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadFloat();
            Unk04 = Reader.ReadInt32();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteFloat(Unk00);
            Writer.WriteInt32(Unk04);
        }
    };

    struct DisableStaminaRegen {
        static constexpr TAE3EventType Type = TAE3EventType::DisableStaminaRegen;
        uint8_t State = {};

        void Read(BinaryReader& Reader) {
            State = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(State);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk226 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk226;
        uint8_t State = {};

        void Read(BinaryReader& Reader) {
            State = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(State);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk227 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk227;
        int32_t Mask = {};

        void Read(BinaryReader& Reader) {
            Mask = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Mask);
            Writer.WriteInt32(0);
        }
    };

    struct RagdollReviveTime {
        static constexpr TAE3EventType Type = TAE3EventType::RagdollReviveTime;
        float Unk00 = {};
        float ReviveTimer = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadFloat();
            ReviveTimer = Reader.ReadFloat();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteFloat(Unk00);
            Writer.WriteFloat(ReviveTimer);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk229 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk229;
        int32_t Unk00 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteInt32(0);
        }
    };

    struct SetEventMessageID {
        static constexpr TAE3EventType Type = TAE3EventType::SetEventMessageID;
        int32_t EventMessageID = {};

        void Read(BinaryReader& Reader) {
            EventMessageID = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(EventMessageID);
            Writer.WriteInt32(0);
        }
    };

    struct Unk232 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk232;
        uint8_t Unk00 = {};
        uint8_t Unk01 = {};
        uint8_t Unk02 = {};
        uint8_t Unk03 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadByte();
            Unk01 = Reader.ReadByte();
            Unk02 = Reader.ReadByte();
            Unk03 = Reader.ReadByte();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(Unk00);
            Writer.WriteByte(Unk01);
            Writer.WriteByte(Unk02);
            Writer.WriteByte(Unk03);
            Writer.WriteInt32(0);
        }
    };

    struct ChangeDrawMask {
        static constexpr TAE3EventType Type = TAE3EventType::ChangeDrawMask;
        std::vector<uint8_t> DrawMask = std::vector<uint8_t>(32);

        void Read(BinaryReader& Reader) {
            DrawMask = Reader.ReadBytes(32);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteBytes(DrawMask);
        }
    };

    struct RollDistanceReduction {
        static constexpr TAE3EventType Type = TAE3EventType::RollDistanceReduction;
        float Unk00 = {};
        float Unk04 = {};
        bool RollType = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadFloat();
            Unk04 = Reader.ReadFloat();
            RollType = Reader.ReadBool();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteFloat(Unk00);
            Writer.WriteFloat(Unk04);
            Writer.WriteBool(RollType);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
        }
    };

    struct CreateAISound {
        static constexpr TAE3EventType Type = TAE3EventType::CreateAISound;
        int32_t AISoundID = {};

        void Read(BinaryReader& Reader) {
            AISoundID = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(AISoundID);
            Writer.WriteInt32(0);
        }
    };

    struct Unk300 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk300;
        int16_t JumpTableID1 = {};
        int16_t JumpTableID2 = {};
        float Unk04 = {};
        float Unk08 = {};
        int32_t Unk0C = {};

        void Read(BinaryReader& Reader) {
            JumpTableID1 = Reader.ReadInt16();
            JumpTableID2 = Reader.ReadInt16();
            Unk04 = Reader.ReadFloat();
            Unk08 = Reader.ReadFloat();
            Unk0C = Reader.ReadInt32();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt16(JumpTableID1);
            Writer.WriteInt16(JumpTableID2);
            Writer.WriteFloat(Unk04);
            Writer.WriteFloat(Unk08);
            Writer.WriteInt32(Unk0C);
        }
    };

    struct Unk301 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk301;
        int32_t Unk00 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteInt32(0);
        }
    };

    struct AddSpEffectDragonForm {
        static constexpr TAE3EventType Type = TAE3EventType::AddSpEffectDragonForm;
        int32_t SpEffectID = {};

        void Read(BinaryReader& Reader) {
            SpEffectID = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(SpEffectID);
            Writer.WriteInt32(0);
        }
    };

    struct PlayAnimation {
        static constexpr TAE3EventType Type = TAE3EventType::PlayAnimation;
        int32_t AnimationID = {};

        void Read(BinaryReader& Reader) {
            AnimationID = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(AnimationID);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct BehaviorThing {
        static constexpr TAE3EventType Type = TAE3EventType::BehaviorThing;
        uint16_t Unk00 = {};
        int16_t Unk02 = {};
        int32_t BehaviorListID = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadUInt16();
            Unk02 = Reader.ReadInt16();
            BehaviorListID = Reader.ReadInt32();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteUInt16(Unk00);
            Writer.WriteInt16(Unk02);
            Writer.WriteInt32(BehaviorListID);
        }
    };

    struct CreateBehaviorPC {
        static constexpr TAE3EventType Type = TAE3EventType::CreateBehaviorPC;
        int16_t Unk00 = {};
        int16_t Unk02 = {};
        int32_t Condition = {};
        int32_t Unk08 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt16();
            Unk02 = Reader.ReadInt16();
            Condition = Reader.ReadInt32();
            Unk08 = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt16(Unk00);
            Writer.WriteInt16(Unk02);
            Writer.WriteInt32(Condition);
            Writer.WriteInt32(Unk08);
            Writer.WriteInt32(0);
        }
    };

    struct Unk308 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk308;
        float Unk00 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadFloat();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteFloat(Unk00);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk310 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk310;
        uint8_t Unk00 = {};
        uint8_t Unk01 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadByte();
            Unk01 = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(Unk00);
            Writer.WriteByte(Unk01);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk311 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk311;
        uint8_t Unk00 = {};
        uint8_t Unk01 = {};
        uint8_t Unk02 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadByte();
            Unk01 = Reader.ReadByte();
            Unk02 = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(Unk00);
            Writer.WriteByte(Unk01);
            Writer.WriteByte(Unk02);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk312 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk312;
        std::vector<uint8_t> BehaviorMask = std::vector<uint8_t>(32);

        void Read(BinaryReader& Reader) {
            BehaviorMask = Reader.ReadBytes(32);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteBytes(BehaviorMask);
        }
    };

    struct Unk320 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk320;
        bool Unk00 = {};
        bool Unk01 = {};
        bool Unk02 = {};
        bool Unk03 = {};
        bool Unk04 = {};
        bool Unk05 = {};
        bool Unk06 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadBool();
            Unk01 = Reader.ReadBool();
            Unk02 = Reader.ReadBool();
            Unk03 = Reader.ReadBool();
            Unk04 = Reader.ReadBool();
            Unk05 = Reader.ReadBool();
            Unk06 = Reader.ReadBool();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteBool(Unk00);
            Writer.WriteBool(Unk01);
            Writer.WriteBool(Unk02);
            Writer.WriteBool(Unk03);
            Writer.WriteBool(Unk04);
            Writer.WriteBool(Unk05);
            Writer.WriteBool(Unk06);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk330 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk330;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct EffectDuringThrow {
        static constexpr TAE3EventType Type = TAE3EventType::EffectDuringThrow;
        int32_t SpEffectID1 = {};
        int32_t SpEffectID2 = {};

        void Read(BinaryReader& Reader) {
            SpEffectID1 = Reader.ReadInt32();
            SpEffectID2 = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(SpEffectID1);
            Writer.WriteInt32(SpEffectID2);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk332 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk332;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct CreateSpEffect {
        static constexpr TAE3EventType Type = TAE3EventType::CreateSpEffect;
        int32_t SpEffectID = {};

        void Read(BinaryReader& Reader) {
            SpEffectID = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(SpEffectID);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk500 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk500;
        uint8_t Unk00 = {};
        uint8_t Unk01 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadByte();
            Unk01 = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(Unk00);
            Writer.WriteByte(Unk01);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk510 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk510;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk520 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk520;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct KingOfTheStorm {
        static constexpr TAE3EventType Type = TAE3EventType::KingOfTheStorm;
        float Unk00 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadFloat();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteFloat(Unk00);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk600 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk600;
        int32_t Mask = {};

        void Read(BinaryReader& Reader) {
            Mask = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Mask);
            Writer.WriteInt32(0);
        }
    };

    struct Unk601 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk601;
        int32_t StayAnimType = {};
        float Unk04 = {};
        float Unk08 = {};

        void Read(BinaryReader& Reader) {
            StayAnimType = Reader.ReadInt32();
            Unk04 = Reader.ReadFloat();
            Unk08 = Reader.ReadFloat();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(StayAnimType);
            Writer.WriteFloat(Unk04);
            Writer.WriteFloat(Unk08);
            Writer.WriteInt32(0);
        }
    };

    struct DebugAnimSpeed {
        static constexpr TAE3EventType Type = TAE3EventType::DebugAnimSpeed;
        uint32_t AnimSpeed = {};

        void Read(BinaryReader& Reader) {
            AnimSpeed = Reader.ReadUInt32();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteUInt32(AnimSpeed);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk605 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk605;
        bool Unk00 = {};
        uint8_t Unk01 = {};
        uint8_t Unk02 = {};
        uint8_t Unk03 = {};
        int32_t Unk04 = {};
        float Unk08 = {};
        float Unk0C = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadBool();
            Unk01 = Reader.ReadByte();
            Unk02 = Reader.ReadByte();
            Unk03 = Reader.ReadByte();
            Unk04 = Reader.ReadInt32();
            Unk08 = Reader.ReadFloat();
            Unk0C = Reader.ReadFloat();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteBool(Unk00);
            Writer.WriteByte(Unk01);
            Writer.WriteByte(Unk02);
            Writer.WriteByte(Unk03);
            Writer.WriteInt32(Unk04);
            Writer.WriteFloat(Unk08);
            Writer.WriteFloat(Unk0C);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk606 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk606;
        uint8_t Unk00 = {};
        uint8_t Unk04 = {};
        uint8_t Unk06 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Unk04 = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Unk06 = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(Unk00);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(Unk04);
            Writer.WriteByte(0);
            Writer.WriteByte(Unk06);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk700 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk700;
        float Unk00 = {};
        float Unk04 = {};
        float Unk08 = {};
        float Unk0C = {};
        int32_t Unk10 = {};
        int8_t Unk14 = {};
        float Unk18 = {};
        float Unk1C = {};
        float Unk20 = {};
        float Unk24 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadFloat();
            Unk04 = Reader.ReadFloat();
            Unk08 = Reader.ReadFloat();
            Unk0C = Reader.ReadFloat();
            Unk10 = Reader.ReadInt32();
            Unk14 = Reader.ReadSByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Unk18 = Reader.ReadFloat();
            Unk1C = Reader.ReadFloat();
            Unk20 = Reader.ReadFloat();
            Unk24 = Reader.ReadFloat();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteFloat(Unk00);
            Writer.WriteFloat(Unk04);
            Writer.WriteFloat(Unk08);
            Writer.WriteFloat(Unk0C);
            Writer.WriteInt32(Unk10);
            Writer.WriteSByte(Unk14);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteFloat(Unk18);
            Writer.WriteFloat(Unk1C);
            Writer.WriteFloat(Unk20);
            Writer.WriteFloat(Unk24);
        }
    };

    struct EnableTurningDirection {
        static constexpr TAE3EventType Type = TAE3EventType::EnableTurningDirection;
        uint8_t State = {};

        void Read(BinaryReader& Reader) {
            State = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(State);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct FacingAngleCorrection {
        static constexpr TAE3EventType Type = TAE3EventType::FacingAngleCorrection;
        float CorrectionRate = {};

        void Read(BinaryReader& Reader) {
            CorrectionRate = Reader.ReadFloat();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteFloat(CorrectionRate);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk707 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk707;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct HideWeapon {
        static constexpr TAE3EventType Type = TAE3EventType::HideWeapon;
        uint8_t Unk00 = {};
        uint8_t Unk01 = {};
        uint8_t Unk02 = {};
        uint8_t Unk03 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadByte();
            Unk01 = Reader.ReadByte();
            Unk02 = Reader.ReadByte();
            Unk03 = Reader.ReadByte();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(Unk00);
            Writer.WriteByte(Unk01);
            Writer.WriteByte(Unk02);
            Writer.WriteByte(Unk03);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct HideModelMask {
        static constexpr TAE3EventType Type = TAE3EventType::HideModelMask;
        std::vector<uint8_t> Mask = std::vector<uint8_t>(32);

        void Read(BinaryReader& Reader) {
            Mask = Reader.ReadBytes(32);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteBytes(Mask);
        }
    };

    struct DamageLevelModule {
        static constexpr TAE3EventType Type = TAE3EventType::DamageLevelModule;
        std::vector<uint8_t> Mask = std::vector<uint8_t>(16);
        uint8_t Unk10 = {};
        uint8_t Unk11 = {};
        uint8_t Unk12 = {};

        void Read(BinaryReader& Reader) {
            Mask = Reader.ReadBytes(16);
            Unk10 = Reader.ReadByte();
            Unk11 = Reader.ReadByte();
            Unk12 = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteBytes(Mask);
            Writer.WriteByte(Unk10);
            Writer.WriteByte(Unk11);
            Writer.WriteByte(Unk12);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct ModelMask {
        static constexpr TAE3EventType Type = TAE3EventType::ModelMask;
        std::vector<uint8_t> Mask = std::vector<uint8_t>(32);

        void Read(BinaryReader& Reader) {
            Mask = Reader.ReadBytes(32);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteBytes(Mask);
        }
    };

    struct DamageLevelFunction {
        static constexpr TAE3EventType Type = TAE3EventType::DamageLevelFunction;
        uint8_t Unk00 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(Unk00);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk715 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk715;
        uint8_t Unk00 = {};
        uint8_t Unk01 = {};
        uint8_t Unk02 = {};
        uint8_t Unk03 = {};
        uint8_t Unk04 = {};
        uint8_t Unk05 = {};
        uint8_t Unk06 = {};
        uint8_t Unk07 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadByte();
            Unk01 = Reader.ReadByte();
            Unk02 = Reader.ReadByte();
            Unk03 = Reader.ReadByte();
            Unk04 = Reader.ReadByte();
            Unk05 = Reader.ReadByte();
            Unk06 = Reader.ReadByte();
            Unk07 = Reader.ReadByte();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(Unk00);
            Writer.WriteByte(Unk01);
            Writer.WriteByte(Unk02);
            Writer.WriteByte(Unk03);
            Writer.WriteByte(Unk04);
            Writer.WriteByte(Unk05);
            Writer.WriteByte(Unk06);
            Writer.WriteByte(Unk07);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct CultStart {
        static constexpr TAE3EventType Type = TAE3EventType::CultStart;
        uint8_t CultType = {};

        void Read(BinaryReader& Reader) {
            CultType = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(CultType);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk730 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk730;
        int32_t Unk00 = {};
        int32_t Unk04 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteInt32(Unk04);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk740 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk740;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct IFrameState {
        static constexpr TAE3EventType Type = TAE3EventType::IFrameState;
        uint8_t Unk00 = {};
        uint8_t Unk01 = {};
        uint8_t Unk02 = {};
        uint8_t Unk03 = {};
        float Unk04 = {};
        float Unk08 = {};
        float Unk0C = {};
        float Unk10 = {};
        float Unk14 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadByte();
            Unk01 = Reader.ReadByte();
            Unk02 = Reader.ReadByte();
            Unk03 = Reader.ReadByte();
            Unk04 = Reader.ReadFloat();
            Unk08 = Reader.ReadFloat();
            Unk0C = Reader.ReadFloat();
            Unk10 = Reader.ReadFloat();
            Unk14 = Reader.ReadFloat();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(Unk00);
            Writer.WriteByte(Unk01);
            Writer.WriteByte(Unk02);
            Writer.WriteByte(Unk03);
            Writer.WriteFloat(Unk04);
            Writer.WriteFloat(Unk08);
            Writer.WriteFloat(Unk0C);
            Writer.WriteFloat(Unk10);
            Writer.WriteFloat(Unk14);
        }
    };

    struct BonePos {
        static constexpr TAE3EventType Type = TAE3EventType::BonePos;
        int32_t Unk00 = {};
        float Unk04 = {};
        uint8_t Unk08 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadFloat();
            Unk08 = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteFloat(Unk04);
            Writer.WriteByte(Unk08);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
        }
    };

    struct BoneFixOn1 {
        static constexpr TAE3EventType Type = TAE3EventType::BoneFixOn1;
        uint8_t BoneID = {};

        void Read(BinaryReader& Reader) {
            BoneID = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(BoneID);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct BoneFixOn2 {
        static constexpr TAE3EventType Type = TAE3EventType::BoneFixOn2;
        int32_t Unk00 = {};
        float Unk04 = {};
        uint8_t Unk08 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt32();
            Unk04 = Reader.ReadFloat();
            Unk08 = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(Unk00);
            Writer.WriteFloat(Unk04);
            Writer.WriteByte(Unk08);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
        }
    };

    struct TurnLowerBody {
        static constexpr TAE3EventType Type = TAE3EventType::TurnLowerBody;
        uint8_t TurnState = {};

        void Read(BinaryReader& Reader) {
            TurnState = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(TurnState);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk782 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk782;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct SpawnBulletByCultSacrifice1 {
        static constexpr TAE3EventType Type = TAE3EventType::SpawnBulletByCultSacrifice1;
        float Unk00 = {};
        int32_t DummyPointID = {};
        int32_t BulletID = {};
        uint8_t Unk0C = {};
        uint8_t Unk0D = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadFloat();
            DummyPointID = Reader.ReadInt32();
            BulletID = Reader.ReadInt32();
            Unk0C = Reader.ReadByte();
            Unk0D = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteFloat(Unk00);
            Writer.WriteInt32(DummyPointID);
            Writer.WriteInt32(BulletID);
            Writer.WriteByte(Unk0C);
            Writer.WriteByte(Unk0D);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
        }
    };

    struct Unk786 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk786;
        float Unk00 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadFloat();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteFloat(Unk00);
            Writer.WriteInt32(0);
        }
    };

    struct Unk790 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk790;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk791 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk791;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct HitEffect2 {
        static constexpr TAE3EventType Type = TAE3EventType::HitEffect2;
        int16_t Unk00 = {};
        int32_t Unk04 = {};
        int32_t Unk08 = {};
        uint8_t Unk0C = {};
        uint8_t Unk0D = {};
        uint8_t Unk0E = {};
        uint8_t Unk0F = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadInt16();
            Reader.Assert<int16_t>(0);
            Unk04 = Reader.ReadInt32();
            Unk08 = Reader.ReadInt32();
            Unk0C = Reader.ReadByte();
            Unk0D = Reader.ReadByte();
            Unk0E = Reader.ReadByte();
            Unk0F = Reader.ReadByte();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt16(Unk00);
            Writer.WriteInt16(0);
            Writer.WriteInt32(Unk04);
            Writer.WriteInt32(Unk08);
            Writer.WriteByte(Unk0C);
            Writer.WriteByte(Unk0D);
            Writer.WriteByte(Unk0E);
            Writer.WriteByte(Unk0F);
        }
    };

    struct CultSacrifice1 {
        static constexpr TAE3EventType Type = TAE3EventType::CultSacrifice1;
        int32_t SacrificeValue = {};

        void Read(BinaryReader& Reader) {
            SacrificeValue = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(SacrificeValue);
            Writer.WriteInt32(0);
        }
    };

    struct SacrificeEmpty {
        static constexpr TAE3EventType Type = TAE3EventType::SacrificeEmpty;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Toughness {
        static constexpr TAE3EventType Type = TAE3EventType::Toughness;
        uint8_t ToughnessParamID = {};
        bool IsToughnessEffective = {};
        float ToughnessRate = {};

        void Read(BinaryReader& Reader) {
            ToughnessParamID = Reader.ReadByte();
            IsToughnessEffective = Reader.ReadBool();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            ToughnessRate = Reader.ReadFloat();
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(ToughnessParamID);
            Writer.WriteBool(IsToughnessEffective);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteFloat(ToughnessRate);
        }
    };

    struct BringCultMenu {
        static constexpr TAE3EventType Type = TAE3EventType::BringCultMenu;
        uint8_t MenuType = {};

        void Read(BinaryReader& Reader) {
            MenuType = Reader.ReadByte();
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<uint8_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteByte(MenuType);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteByte(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct CeremonyParamID {
        static constexpr TAE3EventType Type = TAE3EventType::CeremonyParamID;
        int32_t ParamID = {};

        void Read(BinaryReader& Reader) {
            ParamID = Reader.ReadInt32();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(ParamID);
            Writer.WriteInt32(0);
        }
    };

    struct CultSingle {
        static constexpr TAE3EventType Type = TAE3EventType::CultSingle;
        float Unk00 = {};

        void Read(BinaryReader& Reader) {
            Unk00 = Reader.ReadFloat();
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteFloat(Unk00);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct CultEmpty2 {
        static constexpr TAE3EventType Type = TAE3EventType::CultEmpty2;

        void Read(BinaryReader& Reader) {
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
            Writer.WriteInt32(0);
        }
    };

    struct Unk800 {
        static constexpr TAE3EventType Type = TAE3EventType::Unk800;
        float MetersPerTick = {};
        float MetersOnTurn = {};
        float Unk08 = {};

        void Read(BinaryReader& Reader) {
            MetersPerTick = Reader.ReadFloat();
            MetersOnTurn = Reader.ReadFloat();
            Unk08 = Reader.ReadFloat();
            Reader.Assert<int32_t>(0);
        }

        void Write(BinaryWriter& Writer) const {
            Writer.WriteFloat(MetersPerTick);
            Writer.WriteFloat(MetersOnTurn);
            Writer.WriteFloat(Unk08);
            Writer.WriteInt32(0);
        }
    };

    }  // namespace TAE3Events

    // The data of an event, as the struct for its type.
    using TAE3EventData = std::variant<
        TAE3Events::JumpTable,
        TAE3Events::Unk001,
        TAE3Events::Unk002,
        TAE3Events::Unk005,
        TAE3Events::Unk016,
        TAE3Events::Unk017,
        TAE3Events::Unk024,
        TAE3Events::SwitchWeapon1,
        TAE3Events::SwitchWeapon2,
        TAE3Events::Unk034,
        TAE3Events::Unk035,
        TAE3Events::Unk064,
        TAE3Events::Unk065,
        TAE3Events::CreateSpEffect1,
        TAE3Events::CreateSpEffect2,
        TAE3Events::PlayFFX,
        TAE3Events::Unk110,
        TAE3Events::HitEffect,
        TAE3Events::Unk113,
        TAE3Events::Unk114,
        TAE3Events::Unk115,
        TAE3Events::Unk116,
        TAE3Events::Unk117,
        TAE3Events::Unk118,
        TAE3Events::Unk119,
        TAE3Events::Unk120,
        TAE3Events::Unk121,
        TAE3Events::PlaySound1,
        TAE3Events::PlaySound2,
        TAE3Events::PlaySound3,
        TAE3Events::PlaySound4,
        TAE3Events::PlaySound5,
        TAE3Events::Unk137,
        TAE3Events::CreateDecal,
        TAE3Events::Unk144,
        TAE3Events::Unk145,
        TAE3Events::Unk150,
        TAE3Events::Unk151,
        TAE3Events::Unk161,
        TAE3Events::FadeOut,
        TAE3Events::Unk194,
        TAE3Events::Unk224,
        TAE3Events::DisableStaminaRegen,
        TAE3Events::Unk226,
        TAE3Events::Unk227,
        TAE3Events::RagdollReviveTime,
        TAE3Events::Unk229,
        TAE3Events::SetEventMessageID,
        TAE3Events::Unk232,
        TAE3Events::ChangeDrawMask,
        TAE3Events::RollDistanceReduction,
        TAE3Events::CreateAISound,
        TAE3Events::Unk300,
        TAE3Events::Unk301,
        TAE3Events::AddSpEffectDragonForm,
        TAE3Events::PlayAnimation,
        TAE3Events::BehaviorThing,
        TAE3Events::CreateBehaviorPC,
        TAE3Events::Unk308,
        TAE3Events::Unk310,
        TAE3Events::Unk311,
        TAE3Events::Unk312,
        TAE3Events::Unk320,
        TAE3Events::Unk330,
        TAE3Events::EffectDuringThrow,
        TAE3Events::Unk332,
        TAE3Events::CreateSpEffect,
        TAE3Events::Unk500,
        TAE3Events::Unk510,
        TAE3Events::Unk520,
        TAE3Events::KingOfTheStorm,
        TAE3Events::Unk600,
        TAE3Events::Unk601,
        TAE3Events::DebugAnimSpeed,
        TAE3Events::Unk605,
        TAE3Events::Unk606,
        TAE3Events::Unk700,
        TAE3Events::EnableTurningDirection,
        TAE3Events::FacingAngleCorrection,
        TAE3Events::Unk707,
        TAE3Events::HideWeapon,
        TAE3Events::HideModelMask,
        TAE3Events::DamageLevelModule,
        TAE3Events::ModelMask,
        TAE3Events::DamageLevelFunction,
        TAE3Events::Unk715,
        TAE3Events::CultStart,
        TAE3Events::Unk730,
        TAE3Events::Unk740,
        TAE3Events::IFrameState,
        TAE3Events::BonePos,
        TAE3Events::BoneFixOn1,
        TAE3Events::BoneFixOn2,
        TAE3Events::TurnLowerBody,
        TAE3Events::Unk782,
        TAE3Events::SpawnBulletByCultSacrifice1,
        TAE3Events::Unk786,
        TAE3Events::Unk790,
        TAE3Events::Unk791,
        TAE3Events::HitEffect2,
        TAE3Events::CultSacrifice1,
        TAE3Events::SacrificeEmpty,
        TAE3Events::Toughness,
        TAE3Events::BringCultMenu,
        TAE3Events::CeremonyParamID,
        TAE3Events::CultSingle,
        TAE3Events::CultEmpty2,
        TAE3Events::Unk800
    >;

    // Reads the fields of an event of the given type.
    inline TAE3EventData ReadTAE3EventData(TAE3EventType Type, BinaryReader& Reader) {
        switch (Type) {
            case TAE3EventType::JumpTable: { TAE3Events::JumpTable Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk001: { TAE3Events::Unk001 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk002: { TAE3Events::Unk002 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk005: { TAE3Events::Unk005 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk016: { TAE3Events::Unk016 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk017: { TAE3Events::Unk017 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk024: { TAE3Events::Unk024 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::SwitchWeapon1: { TAE3Events::SwitchWeapon1 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::SwitchWeapon2: { TAE3Events::SwitchWeapon2 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk034: { TAE3Events::Unk034 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk035: { TAE3Events::Unk035 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk064: { TAE3Events::Unk064 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk065: { TAE3Events::Unk065 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::CreateSpEffect1: { TAE3Events::CreateSpEffect1 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::CreateSpEffect2: { TAE3Events::CreateSpEffect2 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::PlayFFX: { TAE3Events::PlayFFX Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk110: { TAE3Events::Unk110 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::HitEffect: { TAE3Events::HitEffect Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk113: { TAE3Events::Unk113 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk114: { TAE3Events::Unk114 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk115: { TAE3Events::Unk115 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk116: { TAE3Events::Unk116 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk117: { TAE3Events::Unk117 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk118: { TAE3Events::Unk118 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk119: { TAE3Events::Unk119 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk120: { TAE3Events::Unk120 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk121: { TAE3Events::Unk121 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::PlaySound1: { TAE3Events::PlaySound1 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::PlaySound2: { TAE3Events::PlaySound2 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::PlaySound3: { TAE3Events::PlaySound3 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::PlaySound4: { TAE3Events::PlaySound4 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::PlaySound5: { TAE3Events::PlaySound5 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk137: { TAE3Events::Unk137 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::CreateDecal: { TAE3Events::CreateDecal Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk144: { TAE3Events::Unk144 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk145: { TAE3Events::Unk145 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk150: { TAE3Events::Unk150 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk151: { TAE3Events::Unk151 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk161: { TAE3Events::Unk161 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::FadeOut: { TAE3Events::FadeOut Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk194: { TAE3Events::Unk194 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk224: { TAE3Events::Unk224 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::DisableStaminaRegen: { TAE3Events::DisableStaminaRegen Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk226: { TAE3Events::Unk226 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk227: { TAE3Events::Unk227 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::RagdollReviveTime: { TAE3Events::RagdollReviveTime Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk229: { TAE3Events::Unk229 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::SetEventMessageID: { TAE3Events::SetEventMessageID Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk232: { TAE3Events::Unk232 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::ChangeDrawMask: { TAE3Events::ChangeDrawMask Value; Value.Read(Reader); return Value; }
            case TAE3EventType::RollDistanceReduction: { TAE3Events::RollDistanceReduction Value; Value.Read(Reader); return Value; }
            case TAE3EventType::CreateAISound: { TAE3Events::CreateAISound Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk300: { TAE3Events::Unk300 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk301: { TAE3Events::Unk301 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::AddSpEffectDragonForm: { TAE3Events::AddSpEffectDragonForm Value; Value.Read(Reader); return Value; }
            case TAE3EventType::PlayAnimation: { TAE3Events::PlayAnimation Value; Value.Read(Reader); return Value; }
            case TAE3EventType::BehaviorThing: { TAE3Events::BehaviorThing Value; Value.Read(Reader); return Value; }
            case TAE3EventType::CreateBehaviorPC: { TAE3Events::CreateBehaviorPC Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk308: { TAE3Events::Unk308 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk310: { TAE3Events::Unk310 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk311: { TAE3Events::Unk311 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk312: { TAE3Events::Unk312 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk320: { TAE3Events::Unk320 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk330: { TAE3Events::Unk330 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::EffectDuringThrow: { TAE3Events::EffectDuringThrow Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk332: { TAE3Events::Unk332 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::CreateSpEffect: { TAE3Events::CreateSpEffect Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk500: { TAE3Events::Unk500 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk510: { TAE3Events::Unk510 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk520: { TAE3Events::Unk520 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::KingOfTheStorm: { TAE3Events::KingOfTheStorm Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk600: { TAE3Events::Unk600 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk601: { TAE3Events::Unk601 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::DebugAnimSpeed: { TAE3Events::DebugAnimSpeed Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk605: { TAE3Events::Unk605 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk606: { TAE3Events::Unk606 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk700: { TAE3Events::Unk700 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::EnableTurningDirection: { TAE3Events::EnableTurningDirection Value; Value.Read(Reader); return Value; }
            case TAE3EventType::FacingAngleCorrection: { TAE3Events::FacingAngleCorrection Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk707: { TAE3Events::Unk707 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::HideWeapon: { TAE3Events::HideWeapon Value; Value.Read(Reader); return Value; }
            case TAE3EventType::HideModelMask: { TAE3Events::HideModelMask Value; Value.Read(Reader); return Value; }
            case TAE3EventType::DamageLevelModule: { TAE3Events::DamageLevelModule Value; Value.Read(Reader); return Value; }
            case TAE3EventType::ModelMask: { TAE3Events::ModelMask Value; Value.Read(Reader); return Value; }
            case TAE3EventType::DamageLevelFunction: { TAE3Events::DamageLevelFunction Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk715: { TAE3Events::Unk715 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::CultStart: { TAE3Events::CultStart Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk730: { TAE3Events::Unk730 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk740: { TAE3Events::Unk740 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::IFrameState: { TAE3Events::IFrameState Value; Value.Read(Reader); return Value; }
            case TAE3EventType::BonePos: { TAE3Events::BonePos Value; Value.Read(Reader); return Value; }
            case TAE3EventType::BoneFixOn1: { TAE3Events::BoneFixOn1 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::BoneFixOn2: { TAE3Events::BoneFixOn2 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::TurnLowerBody: { TAE3Events::TurnLowerBody Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk782: { TAE3Events::Unk782 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::SpawnBulletByCultSacrifice1: { TAE3Events::SpawnBulletByCultSacrifice1 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk786: { TAE3Events::Unk786 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk790: { TAE3Events::Unk790 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk791: { TAE3Events::Unk791 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::HitEffect2: { TAE3Events::HitEffect2 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::CultSacrifice1: { TAE3Events::CultSacrifice1 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::SacrificeEmpty: { TAE3Events::SacrificeEmpty Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Toughness: { TAE3Events::Toughness Value; Value.Read(Reader); return Value; }
            case TAE3EventType::BringCultMenu: { TAE3Events::BringCultMenu Value; Value.Read(Reader); return Value; }
            case TAE3EventType::CeremonyParamID: { TAE3Events::CeremonyParamID Value; Value.Read(Reader); return Value; }
            case TAE3EventType::CultSingle: { TAE3Events::CultSingle Value; Value.Read(Reader); return Value; }
            case TAE3EventType::CultEmpty2: { TAE3Events::CultEmpty2 Value; Value.Read(Reader); return Value; }
            case TAE3EventType::Unk800: { TAE3Events::Unk800 Value; Value.Read(Reader); return Value; }
            default: throw BinaryException("Unsupported TAE event type " + std::to_string(static_cast<uint64_t>(Type)));
        }
    }

    // The type number of the event data's struct.
    inline TAE3EventType TAE3EventTypeOf(const TAE3EventData& Data) {
        return std::visit([](const auto& Value) { return std::decay_t<decltype(Value)>::Type; }, Data);
    }

    inline void WriteTAE3EventData(const TAE3EventData& Data, BinaryWriter& Writer) {
        std::visit([&](const auto& Value) { Value.Write(Writer); }, Data);
    }

}  // namespace Souls
