#!/usr/bin/env python3
"""Generates Source/libSouls/Formats/TAE3Events.hpp from SoulsFormats' TAE3.Event.cs.

TAE3 has over a hundred event types that each hold a few typed fields and are read and written field by field.
Those classes are regular enough to translate mechanically, so the C++ versions are generated rather than copied by
hand. Usage:

    python Tools/GenerateTAE3Events.py <path to TAE3.Event.cs> Source/libSouls/Formats/TAE3Events.hpp

The generated header is checked in; rerun this only if the upstream list of events changes.
"""

import re
import sys

CPP_TYPES = {
    "int": "int32_t", "uint": "uint32_t", "short": "int16_t", "ushort": "uint16_t", "byte": "uint8_t",
    "sbyte": "int8_t", "float": "float", "bool": "bool", "long": "int64_t", "ulong": "uint64_t",
    "byte[]": "std::vector<uint8_t>", "int[]": "std::vector<int32_t>",
}
ASSERT_TYPES = {"Byte": "uint8_t", "SByte": "int8_t", "Int16": "int16_t", "UInt16": "uint16_t", "Int32": "int32_t",
                "UInt32": "uint32_t", "Int64": "int64_t", "UInt64": "uint64_t", "Single": "float"}
READ_RENAMES = {"ReadBoolean": "ReadBool", "ReadSingle": "ReadFloat"}
WRITE_RENAMES = {"WriteBoolean": "WriteBool", "WriteSingle": "WriteFloat"}


def main():
    source_path, output_path = sys.argv[1], sys.argv[2]
    text = open(source_path, encoding="utf-8-sig").read()

    enum_body = re.search(r"public enum EventType : ulong\s*\{(.*?)\n\s*\}", text, re.S).group(1)
    enum_entries = re.findall(r"^\s*(\w+)\s*=\s*(\d+),", enum_body, re.M)

    classes = []
    for match in re.finditer(r"public class (\w+) : Event[^\n]*\n\s*\{", text):
        name = match.group(1)
        start = match.end()
        depth = 1
        i = start
        while depth:
            c = text[i]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
            i += 1
        classes.append((name, text[start:i - 1]))

    out = []
    out.append("""//
// Generated by Tools/GenerateTAE3Events.py from SoulsFormats' TAE3.Event.cs. Do not edit by hand.
//

#pragma once

#include <libSouls/BinaryReader.hpp>
#include <libSouls/BinaryWriter.hpp>

#include <cstdint>
#include <variant>
#include <vector>

namespace Souls {

    // Determines the behavior of an event and what data it contains.
    enum class TAE3EventType : uint64_t {""")
    for name, value in enum_entries:
        out.append(f"        {name} = {int(value)},")
    out.append("    };\n")
    out.append("    // One struct per event type, holding the fields that follow the event's header in the file.")
    out.append("    namespace TAE3Events {\n")

    problems = []
    class_infos = []
    for name, body in classes:
        type_match = re.search(r"Type => EventType\.(\w+)", body)
        if not type_match:
            problems.append(f"{name}: no Type")
            continue
        event_type = type_match.group(1)

        # Constructor taking the reader.
        ctor = re.search(r"internal " + name + r"\(float startTime, float endTime, BinaryReaderEx br\) : base\(startTime, endTime\)\s*(\{.*?\n\s{16}\}|\{ \})", body, re.S)
        write = re.search(r"internal override void WriteSpecific\(BinaryWriterEx bw\)\s*(\{.*?\n\s{16}\}|\{ \})", body, re.S)
        if not ctor or not write:
            problems.append(f"{name}: missing read or write")
            continue

        fields = []
        for fm in re.finditer(r"^\s{16}public (byte\[\]|int\[\]|\w+) ([\w, ]+?)(?: \{ get; (?:private )?set; \}|;)", body, re.M):
            for field_name in fm.group(2).split(","):
                fields.append((fm.group(1), field_name.strip()))
        field_types = dict((n, t) for t, n in fields)

        array_sizes = {}
        read_lines = []
        for line in ctor.group(1).strip("{} \n").split("\n"):
            line = re.sub(r"\s*//.*$", "", line).strip()
            if not line:
                continue
            m = re.fullmatch(r"(\w+) = br\.(\w+)\((.*)\);", line)
            if m:
                field, fn, args = m.groups()
                if fn == "ReadBytes":
                    array_sizes[field] = args
                    read_lines.append(f"{field} = Reader.ReadBytes({args});")
                elif fn == "ReadInt32s":
                    array_sizes[field] = args
                    read_lines.append(f"{field} = Reader.ReadArray<int32_t>({args});")
                else:
                    read_lines.append(f"{field} = Reader.{READ_RENAMES.get(fn, fn)}({args});")
                continue
            m = re.fullmatch(r"br\.Assert(\w+)\((.*)\);", line)
            if m and m.group(1) in ASSERT_TYPES:
                read_lines.append(f"Reader.Assert<{ASSERT_TYPES[m.group(1)]}>({m.group(2)});")
                continue
            problems.append(f"{name}: unhandled read: {line}")

        write_lines = []
        for line in write.group(1).strip("{} \n").split("\n"):
            line = re.sub(r"\s*//.*$", "", line).strip()
            if not line:
                continue
            m = re.fullmatch(r"bw\.(\w+)\((.*)\);", line)
            if m:
                fn, args = m.groups()
                if fn == "WriteInt32s":
                    write_lines.append(f"Writer.WriteArray({args});")
                else:
                    write_lines.append(f"Writer.{WRITE_RENAMES.get(fn, fn)}({args});")
                continue
            problems.append(f"{name}: unhandled write: {line}")

        out.append(f"    struct {name} {{")
        out.append(f"        static constexpr TAE3EventType Type = TAE3EventType::{event_type};")
        for cs_type, field in fields:
            cpp = CPP_TYPES.get(cs_type)
            if cpp is None:
                problems.append(f"{name}: unknown field type {cs_type}")
                continue
            if cs_type == "byte[]":
                out.append(f"        {cpp} {field} = std::vector<uint8_t>({array_sizes.get(field, '0')});")
            elif cs_type == "int[]":
                out.append(f"        {cpp} {field} = std::vector<int32_t>({array_sizes.get(field, '0')});")
            else:
                out.append(f"        {cpp} {field} = {{}};")
        out.append("")
        out.append("        void Read(BinaryReader& Reader) {")
        if not read_lines:
            out.append("            (void)Reader;")
        for l in read_lines:
            out.append(f"            {l}")
        out.append("        }")
        out.append("")
        out.append("        void Write(BinaryWriter& Writer) const {")
        if not write_lines:
            out.append("            (void)Writer;")
        for l in write_lines:
            out.append(f"            {l}")
        out.append("        }")
        out.append("    };\n")
        class_infos.append((name, event_type))

    out.append("    }  // namespace TAE3Events\n")
    out.append("    // The data of an event, as the struct for its type.")
    out.append("    using TAE3EventData = std::variant<")
    out.append(",\n".join(f"        TAE3Events::{n}" for n, _ in class_infos))
    out.append("    >;\n")
    out.append("    // Reads the fields of an event of the given type.")
    out.append("    inline TAE3EventData ReadTAE3EventData(TAE3EventType Type, BinaryReader& Reader) {")
    out.append("        switch (Type) {")
    for n, t in class_infos:
        out.append(f"            case TAE3EventType::{t}: {{ TAE3Events::{n} Value; Value.Read(Reader); return Value; }}")
    out.append("            default: throw BinaryException(\"Unsupported TAE event type \" + std::to_string(static_cast<uint64_t>(Type)));")
    out.append("        }")
    out.append("    }\n")
    out.append("    // The type number of the event data's struct.")
    out.append("    inline TAE3EventType TAE3EventTypeOf(const TAE3EventData& Data) {")
    out.append("        return std::visit([](const auto& Value) { return std::decay_t<decltype(Value)>::Type; }, Data);")
    out.append("    }\n")
    out.append("    inline void WriteTAE3EventData(const TAE3EventData& Data, BinaryWriter& Writer) {")
    out.append("        std::visit([&](const auto& Value) { Value.Write(Writer); }, Data);")
    out.append("    }\n")
    out.append("}  // namespace Souls")

    open(output_path, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print(f"{len(class_infos)} event structs written")
    for p in problems:
        print("PROBLEM:", p)


main()
